### ISSUE TITLE
关于对新浪微博数据集的处理

### ISSUE THREAD

**Issue by w1354920787** [CaoQi92/CoupledGNN#1]
请问你们对新浪微博的数据集具体是怎么进行处理的呢？
utils.py 文件中 load_data() 的注释说 ind.dataset_str.***.x 和 ind.dataset_str.***.y 分别是观察到的数据和预测的数据，那么它们在新浪微博的数据集中具体是指的什么？是某一条微博的转发者之类的吗？
如果可以的话，能不能将你们处理之后的新浪微博的数据集上传一下呢？
非常感谢

**Comment by b3y0nd** [comment]
作者您好，我发现一个问题想请教一下，请问您models.py文件中CoupledGNN类中实现的其实是论文中您用来做对比的Single-GCN模型的代码吗？而并非是CoupledGNN的代码，能提供一下的CoupledGNN模型实现吗？万分感谢

**Comment by b3y0nd** [comment]
> 请问你们对新浪微博的数据集具体是怎么进行处理的呢？
> utils.py 文件中 load_data() 的注释说 ind.dataset_str._**.x 和 ind.dataset_str.**_.y 分别是观察到的数据和预测的数据，那么它们在新浪微博的数据集中具体是指的什么？是某一条微博的转发者之类的吗？
> 如果可以的话，能不能将你们处理之后的新浪微博的数据集上传一下呢？
> 非常感谢



> 请问你们对新浪微博的数据集具体是怎么进行处理的呢？
> utils.py文件中load_data（）的注释说ind.dataset_str。_**.x和ind.dataset_str。**_.y分别是观察到的数据和预测的数据，那么它们在新浪微博的数据集中具体是指的什么？是某些条微博的转发者之类的吗？
> 如果可以的话，能不能将你们处理之后的新浪微博的数据集上传一下呢？？
> 非常感谢

同问，希望作者能提供一下预处理思路或代码~

**Comment by CaoQi92** [comment]
您好，关于ind.dataset_str.x和ind.dataset_str.y的含义在utils.py文件中的load_data()函数中有简单介绍，即：
ind.dataset_str.***.x => a list recording the observation for each sample, x[i] = [(t1,u1),(t2,u2),...,(tn,un)]
ind.dataset_str.***.y => a list recording the prediction for each sample, y[i] = dict(u1,u2,...,un)

具体来说在新浪微博场景下，x指的是观测窗口内每个转发用户和转发时间构成的pair对，即（转发时间t1，转发用户u2），按照时间先后顺序所形成的数组。y指的是最终所有转发用户所形成的dict字典。

关于数据预处理的思路在论文5.1.2小节比较详细地描述了~后续如果需要，我会再匿名化处理一下我们使用的新浪微博数据集，然后再考虑进行上传。

**Comment by w1354920787** [comment]
> 具体来说在新浪微博场景下，x指的是观测窗口内每个转发用户和转发时间构成的pair对，即（转发时间t1，转发用户u2），按照时间先后顺序所形成的数组。y指的是最终所有转发用户所形成的dict字典。

非常感谢您的说明
